GET http://localhost:5000/students
Content-Type: application/json

{
    "name": "Prakash Kumar",
    "subscribedToChannel": "Technical Pegasus"
}
###

GET http://localhost:5000/students/2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w

{
    "name": "Prakash Kumar",
    "subscribedToChannel": "Technical Pegasus",
    "secondname": "Ramesh"
}
